spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/renren_security?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
# 微信公众号
weCat:
  appId: wx06bec68a22884722
  appSecret: 5a9bc72b8e6d126757f4be79874bf54b
  mchId: 1550620091
  key: AABBCCDDEEFFGGHHJJKKLLMMNNOOQQPP
  certP12: D:/cert/apiclient_cert.p12
  accessTokenByCodeUrl: https://api.weixin.qq.com/sns/oauth2/access_token
  userInfoUrl: https://api.weixin.qq.com/sns/userinfo
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  ticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket
  payApi: https://api.mch.weixin.qq.com/pay/unifiedorder
  enterprisesPay_API: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
  dnbx_token: weixinMsg
  download_media_url: http://file.api.weixin.qq.com/cgi-bin/media/get?access_token=ACCESS_TOKEN&media_id=MEDIA_ID
  online_kf_list: https://api.weixin.qq.com/cgi-bin/customservice/getonlinekflist

# 百度地图
baiduMap:
  ak: SoQCCsGE9S8ILEvx1HCtV8S6oS4PYYXA
  locationUrl: http://api.map.baidu.com/place/v2/search
  distanceUrl: http://api.map.baidu.com/routematrix/v2/driving

# 美团
meituan:
  appKey: a47e6d93e90e87b0
  appSecret: 9bd1648712f0456a8ede514077e80a8ac00b4ffe
  redirect_url: /cake-api/api/meituan/authRedirect
  sessionUrl: https://openapi.dianping.com/router/oauth/token
  checkCodeUrl: https://openapi.dianping.com/router/tuangou/receipt/prepare
