spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/renren_security?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: renren
      password: 2710482
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
# 微信公众号
weCat:
  appId: wxb591ed4db0694bca
  appSecret: 9d3487c9493ab308bc48f32e09a435bf
  mchId: 1491029172
  key: AABBCCDDEEFFGGHHJJKKLLMMNNOOQQPP
  certP12: D:/cert/apiclient_cert.p12
  accessTokenByCodeUrl: https://api.weixin.qq.com/sns/oauth2/access_token
  userInfoUrl: https://api.weixin.qq.com/sns/userinfo
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token
  ticketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket
  payApi: https://api.mch.weixin.qq.com/pay/unifiedorder
  enterprisesPay_API: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
  dnbx_token: weixinMsg
  download_media_url: http://file.api.weixin.qq.com/cgi-bin/media/get?access_token=ACCESS_TOKEN&media_id=MEDIA_ID
  online_kf_list: https://api.weixin.qq.com/cgi-bin/customservice/getonlinekflist