CREATE TABLE `tb_seller` (
  `seller_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `nick_name` varchar(50) DEFAULT NULL COMMENT '店铺名称',
  `password` varchar(60) DEFAULT NULL COMMENT '密码',
  `email` varchar(40) DEFAULT NULL COMMENT 'EMAIL',
  `mobile` varchar(20) DEFAULT NULL COMMENT '公司手机',
  `telephone` varchar(50) DEFAULT NULL COMMENT '公L司电话',
  `status` varchar(1) DEFAULT '0' COMMENT '状态',
  `region` varchar(20) DEFAULT '0' COMMENT '区域',
  `address_detail` varchar(100) DEFAULT NULL COMMENT '详细地址',
  `linkman_name` varchar(50) DEFAULT NULL COMMENT '联系人姓名',
  `linkman_qq` varchar(13) DEFAULT NULL COMMENT '联系人QQ',
  `linkman_mobile` varchar(20) DEFAULT NULL COMMENT '联系人电话',
  `linkman_email` varchar(40) DEFAULT NULL COMMENT '联系人EMAIL',
  `linkman_jod` varchar(50) DEFAULT NULL COMMENT '职位',
  `Store_Size` varchar(50) DEFAULT NULL COMMENT '是否连锁经营',
  `address_ground` varchar(50) DEFAULT NULL COMMENT '是否支持地推',
  `linkman_operation` varchar(50) DEFAULT NULL COMMENT '店面大小',
  `license_number` varchar(20) DEFAULT NULL COMMENT '营业执照号',
  `tax_number` varchar(20) DEFAULT NULL COMMENT '税务登记证号',
  `org_number` varchar(20) DEFAULT NULL COMMENT '组织机构代码',
  `address` varchar(30) DEFAULT NULL COMMENT '公司地址',
  `address_shop` varchar(100) DEFAULT NULL COMMENT '奶茶店周边',
  `brief` varchar(2000) DEFAULT NULL COMMENT '简介',
  `create_time` datetime DEFAULT NULL COMMENT '创建日期',
  `legal_person` varchar(40) DEFAULT NULL COMMENT '法定代表人',
  `address_distance` varchar(25) DEFAULT NULL COMMENT '距离周边距离',
  `shop_category` varchar(50) DEFAULT NULL COMMENT '分类',
  `shop_lv` varchar(100) DEFAULT NULL COMMENT '门店合作等级',
  `Conversion_rate` varchar(20) DEFAULT NULL COMMENT '转化率',
  PRIMARY KEY (`seller_id`)
) ENGINE=InnoDB AUTO_INCREMENT=11672729288875 DEFAULT CHARSET=utf8 COMMENT='商家'
